### PR TITLE
Fix requires-python

### PR DESCRIPTION
**Pull request by akaszynski**
Installation fails when using Python 3.12.4
```
ERROR: Package 'pyoma-2' requires a different Python: 3.12.4 not in '<=3.12,>=3.8'
```

This PR fixes the python requires by simply setting the upper limit to `<3.12`, thus covering all `3.12.X`.

### CODE REVIEW

**Comment by dfm88** [comment]
Hi @akaszynski thank you for your contribution, can you kindly check if you are downloading the current version? Support for python 3.12 should have been added from v0.5.1 (https://github.com/dagghe/pyOMA2/releases/tag/v0.5.1) and tests on that version of python passes (https://github.com/dagghe/pyOMA2/actions/runs/8654979937). Thanks

**Comment by akaszynski** [comment]
> Hi @akaszynski thank you for your contribution, can you kindly check if you are downloading the current version? Support for python 3.12 should have been added from v0.5.1 (https://github.com/dagghe/pyOMA2/releases/tag/v0.5.1) and tests on that version of python passes (https://github.com/dagghe/pyOMA2/actions/runs/8654979937). Thanks

Turns out that the python environment for 3.12 isn't resolving correctly for Ubuntu or MacOS. See:
https://github.com/dagghe/pyOMA2/actions/runs/9181281196/job/25247651952#step:7:12

```
2024-05-21T20:49:57.5592860Z ============================= test session starts ==============================
2024-05-21T20:49:57.5594100Z platform darwin -- Python 3.11.9, pytest-7.4.4, pluggy-1.3.0
2024-05-21T20:49:57.5594700Z rootdir: /Users/runner/work/pyOMA2/pyOMA2
2024-05-21T20:49:57.5595370Z plugins: anyio-4.3.0, cov-4.1.0
```

However, updating to `pdm` v2.17.2 fixes the environment creation. However, is causes the dependency install to fail because the proper version of numpy can't be resolved. See the workflow run which uses the updated `pdm`:
https://github.com/akaszynski/pyOMA2/actions/runs/10183661296/job/28169155716

Note, this works just fine with `pip`, but if you're using `pdm`, the only workaround is to stop testing Python 3.9 and bump numpy to >= v1.26. It's the oldest version that supports Python 3.12, but numpy dropped Python 3.9.

**Comment by dfm88** [comment]
Oh great, thank you for the insight, we would like to keep PDM as dependency manager and to support until python 3.8 included. If you want to deepen the problem, probably there is a way in pdm to specify different dependency depending on python version and also on platform https://pdm-project.org/en/latest/usage/lock-targets/. Just let us know if you want to give it a try :)

**Comment by akaszynski** [comment]
I think I figured it out in [f30cf1b](https://github.com/dagghe/pyOMA2/pull/15/commits/f30cf1b219f4e2448c08ff28152d18e727917903). Thanks for the tip regarding [lock-targets](https://pdm-project.org/en/latest/usage/lock-targets/).

**Comment by dfm88** [comment]
Great :D thank you I'll mege it

**Pull request merged**
